<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>

    // function oneMore() {
    //   console.log('one more');
    // }
    // async function run() {
    //   console.log('run run');
    //   setTimeout(() => {
    //     console.log('wow');
    //   }, 0);
    //   new Promise((resolve) => {
    //     console.log('hi');
    //     resolve('hi');
    //   }).then((res) => {
    //     console.log(res);
    //   });
    //   oneMore();
    // }
    // setTimeout(run, 1000);






    // test01 = console.log
    // test01('hello 1')
    // test02 = (msg) => console.log(msg)
    // test02('hello 2')






    function oneMore() {
      console.log('one more');
    }
    async function run() {
      console.log('run run');
      setTimeout(() => {
        console.log('wow');
      }, 0);
      new Promise((resolve) => {
        console.log('hi');
        resolve('hi');
      })
      .then(console.log);
      oneMore();
    }
    setTimeout(run, 1000);






    // function haribo(isValid) {
    //   return new Promise((resolve, reject) => {
    //     if (isValid) {
    //       resolve('성공 킹아')
    //     } else {
    //       reject(new Error('실패 뚀륵'))
    //     }
    //   })
    // }
    // haribo(false)
    //   .then(console.log)
    //   .catch(console.error)
    // setTimeout(() => {
    //   console.log('알잘딱')
    // }, 0)
    // haribo(true)
    //   .then(console.log)
    //   .catch(console.error)
    // // '성공 킹아' 가 먼저 출력된 이후에 '실패 뚀륵' 에러가 출력되는 것으로 보아
    // // 태스크큐에서 catch 의 우선순위는 then 보다 낮은 듯하다.
    


  </script>
</body>
</html>